silktide.settings:
  type: config_object
  label: 'Silktide Configuration'
  mapping:
    apikey:
      type: text
      label: 'The Silktide API key'
    lastnotified_time:

    silktide:
      type: mapping
      mapping:
        apikey:
          type: text
          label: 'API key'
          text: 'The Silktide API key as show in your Silktide account'
